"""
Configuration file for CineSemantics Movie Recommendation Engine
Contains all configurable parameters for text and image embeddings, 
database connections, and search functionality.
"""
# MODEL CONFIGURATIONS
TEXT_MODEL_NAME = 'sentence-transformers/all-MiniLM-L6-v2'
TEXT_EMBEDDING_DIMENSION = 384

IMAGE_MODEL_NAME = 'openai/clip-vit-base-patch32'
IMAGE_EMBEDDING_DIMENSION = 512

# DATABASE CONFIGURATIONS
MILVUS_HOST = 'localhost'
MILVUS_PORT = '19530'
MILVUS_DEFAULT_SERVER_HOST = '127.0.0.1'

TEXT_COLLECTION_NAME = 'movie_collection'
IMAGE_COLLECTION_NAME = 'movie_posters'

INDEX_METRIC_TYPE = 'IP'
INDEX_TYPE = 'IVF_FLAT'
INDEX_NLIST = 128

SEARCH_METRIC_TYPE = 'IP'
SEARCH_NPROBE = 10
SEARCH_MULTIPLIER = 3

# DATA PROCESSING CONFIGURATIONS
DEFAULT_BATCH_SIZE = 32
MIN_BATCH_SIZE = 1
MAX_BATCH_SIZE = 128
INSERT_BATCH_SIZE = 100

DEFAULT_TEXT_COLUMN = 'Overview'

VALID_IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.webp', '.bmp', '.gif'}

# FIELD LENGTH LIMITS
TEXT_TITLE_MAX_LENGTH = 1000
TEXT_OVERVIEW_MAX_LENGTH = 20000
TEXT_RELEASE_DATE_MAX_LENGTH = 50
TEXT_GENRE_MAX_LENGTH = 200
TEXT_ORIGINAL_LANGUAGE_MAX_LENGTH = 200
TEXT_POSTER_URL_MAX_LENGTH = 1000

IMAGE_TITLE_MAX_LENGTH = 500
IMAGE_FILENAME_MAX_LENGTH = 500
IMAGE_PATH_MAX_LENGTH = 1000

GENRE_DISPLAY_MAX_LENGTH = 30

# VALIDATION RANGES
MIN_YEAR = 1800
MAX_YEAR = 2100
DATE_FORMAT_PATTERN = r'^\d{4}-\d{2}-\d{2}$'

MIN_RATING = 0.0
MAX_RATING = 10.0

MIN_POPULARITY = 0.0

MAX_QUERY_LIMIT = 16384

# DEFAULT VALUES
DEFAULT_FLOAT_VALUE = 0.0
DEFAULT_INT_VALUE = 0
DEFAULT_STRING_VALUE = ''

DEFAULT_TOP_K = 10

# FILE PATHS (for main scripts)
DEFAULT_IMAGES_FOLDER = '../posters'
DEFAULT_CSV_PATH = '../data/9000plus.csv'

# LOGGING CONFIGURATION
LOG_LEVEL = 'INFO'
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'